{{- if .Values.externalSecrets.enabled -}}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "interview-backend.fullname" . }}-secrets
  namespace: {{ include "interview-backend.namespaceName" . }}
  labels:
    {{- include "interview-backend.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef.name }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind }}
  target:
    name: {{ include "interview-backend.fullname" . }}-secrets
    creationPolicy: {{ .Values.externalSecrets.target.creationPolicy }}
    deletionPolicy: {{ .Values.externalSecrets.target.deletionPolicy }}
  data:
  {{- range .Values.externalSecrets.data }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ $.Values.externalSecrets.remoteRef.path }}
        property: {{ .remoteKey }}
  {{- end }}
{{- end }}
