{{- if .Values.istio.gateway.enabled -}}
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ include "interview-backend.fullname" . }}
  namespace: {{ include "interview-backend.namespaceName" . }}
  labels:
    {{- include "interview-backend.labels" . | nindent 4 }}
spec:
  selector:
    istio: ingress
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - {{ .Values.istio.gateway.host | quote }}
{{- end -}}
