{{- if .Values.namespace.create -}}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "interview-backend.namespaceName" . }}
  labels:
  {{- include "interview-backend.labels" . | nindent 4 }}
  {{- with .Values.namespace.labels }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
