apiVersion: telemetry.istio.io/v1
kind: Telemetry
metadata:
  name: mesh-default
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "istio-chart.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: post-install
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  tracing:
    - providers:
        - name: otel-tracing
      randomSamplingPercentage: 100.0
