{{- if .Values.grafana.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: grafana
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "observability-stack.labels" . | nindent 4 }}
spec:
  hosts:
    - grafana
    - grafana.local
  gateways:
    - mesh
    - istio-ingress/observability-gateway
  http:
    - route:
        - destination:
            host: grafana
            port:
              number: 80
---
{{- end }}
{{- if index .Values "prometheus" "enabled" }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: observability-stack-prometheus-server
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "observability-stack.labels" . | nindent 4 }}
spec:
  hosts:
    - observability-stack-prometheus-server
  http:
    - route:
        - destination:
            host: observability-stack-prometheus-server
            port:
              number: 80
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: observability-stack-prometheus-alertmanager
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "observability-stack.labels" . | nindent 4 }}
spec:
  hosts:
    - observability-stack-prometheus-alertmanager
  http:
    - route:
        - destination:
            host: observability-stack-prometheus-alertmanager
            port:
              number: 9093
---
{{- end }}
{{- if .Values.loki.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: loki
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "observability-stack.labels" . | nindent 4 }}
spec:
  hosts:
    - loki
  http:
    - route:
        - destination:
            host: loki
            port:
              number: 3100
---
{{- end }}
{{- if .Values.tempo.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: tempo
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "observability-stack.labels" . | nindent 4 }}
spec:
  hosts:
    - tempo
  http:
    - match:
        - port: 4317
      route:
        - destination:
            host: tempo
            port:
              number: 4317
    - route:
        - destination:
            host: tempo
            port:
              number: 3200
---
{{- end }}
{{- if index .Values "k8s-monitoring" "enabled" }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: observability-stack-receiver
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "observability-stack.labels" . | nindent 4 }}
spec:
  hosts:
    - observability-stack-receiver
  http:
    - route:
        - destination:
            host: observability-stack-receiver
            port:
              number: 4317
{{- end }}