{{- if .Values.repo.secret.useExternalSecret -}}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-repo-interview
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "argocd-chart.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.repo.secret.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.repo.secret.externalSecret.secretStoreRef.name }}
    kind: {{ .Values.repo.secret.externalSecret.secretStoreRef.kind }}
  target:
    name: argocd-repo-interview
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      data:
        type: git
        url: {{ .Values.repo.url | quote }}
        sshPrivateKey: "{{ "{{ .sshPrivateKey }}" }}"
  data:
    - secretKey: sshPrivateKey
      remoteRef:
        key: {{ .Values.repo.secret.externalSecret.remoteRef.key }}
        property: {{ .Values.repo.secret.externalSecret.remoteRef.property }}
{{- end }}
